### PR TITLE
Fixed a JavaScript bug

### PR DESCRIPTION
**Pull request by egorsmkv**
It is a fix for issue #2

### CODE REVIEW

**Comment by R-J** [comment]
Thanks for the contribution! I guess that you are right in that those colons are needed, but I'm not sure they should be placed there. Let me show it with an example. Here is HTML which is generated by the editor:

~~~
<span
  class="editor-action emoji-neutral editor-dialog-fire-close emoji-wrap"
  data-wysihtml5-command="insertHTML"
  data-wysihtml5-command-value=" :neutral: "
  title=":neutral:"
  data-editor="{"action":"emoji","value":":neutral:"}"
>

<img class="emoji" src="/plugins/EmojiExtender/emoji/yahoo/neutral.gif" title=":neutral:" alt=":neutral:" />

</span>
~~~

As you can see the ":" is everywhere. So it should be added everywhere.

But: I pass the emoji **alias** to my JS. So what if I have the alias `:D`. Wouldn't that end up in `::D:`?

I guess I have to also change the php source...

**Comment by R-J** [comment]
And another I have noticed right now is that I already have a lot of information in gdn.definition('emoji'). Only the info of the emojis shown by the editor is missing. I pass the info from my plugin to the script like that:
~~~

"HiddenEmojis": [
--
  | {
  | "alias": -1,
  | "html": "<img class=\"emoji\" src=\"\/plugins\/EmojiExtender\/emoji\/twitter\/-1.png\" title=\"-1\" alt=\"-1\" height=\"18\" \/>"
  | },
  | {
  | "alias": "+1",
  | "html": "<img class=\"emoji\" src=\"\/plugins\/EmojiExtender\/emoji\/twitter\/+1.png\" title=\"+1\" alt=\"+1\" height=\"18\" \/>"
  | },
~~~

But I guess it would be way more efficient (and better) to only stuff an array of the emojis which are already shown by the editor and use everything else from the emoji definition.

I have to investigate if I can reuse something from the editor for that.

**Comment by egorsmkv** [comment]
> But: I pass the emoji alias to my JS. So what if I have the alias :D. Wouldn't that end up in ::D:?

For those use cases we can add checking if the alias starts with ":" and don't add unnecessary colons.

**Comment by R-J** [comment]
I'm doing a "major" change and will rewrite the JS. This is what  the editor inserts into the HTML source:
~~~

"emoji": {
--
   "assetPath": "\/plugins\/EmojiExtender\/emoji\/twitter",
   "format": "<img class=\"emoji\" src=\"{src}\" title=\"{name}\" alt=\"{name}\" height=\"18\" \/>",
   "emoji": {
   "-1": "-1.png",
   "+1": "+1.png",
   "angry": "angry.png",
   "anguished": "anguished.png",
   "astonished": "astonished.png",
   "bawling": "bawling.png",
   "bleep_bloop": "bleep_bloop.png",
 ...
~~~

This is what my plugin inserts now:
~~~
    "EditorEmojis": [
        "smile",
        "smiley",
        "wink",
...
~~~

Now I do a loop over all the emojis in the first list and if the element is not in the second list, I add it to my container, using the format that is also passed in that gdn.definition('emoji')

**Comment by egorsmkv** [comment]
Okay :)

**Comment by egorsmkv** [comment]
Close the PR because it unneeded.

**Pull request closed without merging**
